=== Auragen-dev/twin-cities-project/Xml's/ind_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- 
    ==================================================================
    This is the schema for the individual metafile. 
    See individual_metafile_example.xml for a valid example instance. 
    Ensure your individual_metafile.xml is validated against this schema 
    using Oxygen or some other validator.
    DO NOT EDIT OR CHANGE THIS FILE UNDER ANY CIRCUMSTANCES 
    ==================================================================
  -->
    <xs:element name="individual_metafile">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="group">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="group_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="student">
                    <xs:complexType>
                        <xs:attribute name="id" use="required" type="student_idType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="component" maxOccurs="1">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="description" type="txtType"/>
                            <xs:element name="problems" type="txtType"/>
                            <xs:element name="solutions" type="txtType"/>
                            <xs:element name="hours_effort" type="hours_effortType"/>
                            <xs:element name="technologies">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tech" minOccurs="2" maxOccurs="6" type="techType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="source_files">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="file" minOccurs="1" maxOccurs="4">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="name" type="xs:string"/>
                                                    <xs:element name="purpose" type="xs:string"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" use="required" type="cmpType"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="security_discussion" maxOccurs="1" type="txtType"/>
                <xs:element name="individual_comment" maxOccurs="1" type="txtType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name="techType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="php"/>
            <xs:enumeration value="xml"/>
            <xs:enumeration value="xslt"/>
            <xs:enumeration value="xsd"/>
            <xs:enumeration value="sql"/>
            <xs:enumeration value="html5"/>
            <xs:enumeration value="css"/>
            <xs:enumeration value="javascript"/>
            <xs:enumeration value="mysql"/>
            <xs:enumeration value="json"/>
            <xs:enumeration value="er-modelling"/>
            <xs:enumeration value="other"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="group_idType">
        <xs:restriction base="xs:string">
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="student_idType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="19024502"/>
            <xs:enumeration value="19014271"/>
            <xs:enumeration value="19045493"/>
            <xs:enumeration value="19045503"/>
            <xs:enumeration value="19045570"/>
            <xs:enumeration value="19045499"/>
            <xs:enumeration value="19045504"/>
            <xs:enumeration value="19033092"/>
            <xs:enumeration value="19032780"/>
            <xs:enumeration value="19033677"/>
            <xs:enumeration value="19034434"/>
            <xs:enumeration value="18042344"/>
            <xs:enumeration value="19045573"/>
            <xs:enumeration value="20050507"/>
            <xs:enumeration value="19047150"/>
            <xs:enumeration value="19019472"/>
            <xs:enumeration value="19045502"/>
            <xs:enumeration value="17042812"/>
            <xs:enumeration value="19042129"/>
            <xs:enumeration value="19008369"/>
            <xs:enumeration value="19045544"/>
            <xs:enumeration value="19045613"/>
            <xs:enumeration value="19010714"/>
            <xs:enumeration value="19036548"/>
            <xs:enumeration value="19020796"/>
            <xs:enumeration value="19021104"/>
            <xs:enumeration value="18012433"/>
            <xs:enumeration value="17011254"/>
            <xs:enumeration value="19036030"/>
            <xs:enumeration value="19023838"/>
            <xs:enumeration value="20044345"/>
            <xs:enumeration value="19019337"/>
            <xs:enumeration value="19044793"/>
            <xs:enumeration value="19027149"/>
            <xs:enumeration value="19010205"/>
            <xs:enumeration value="19034920"/>
            <xs:enumeration value="17023154"/>
            <xs:enumeration value="18026311"/>
            <xs:enumeration value="19022296"/>
            <xs:enumeration value="18022288"/>
            <xs:enumeration value="18030594"/>
            <xs:enumeration value="19029110"/>
            <xs:enumeration value="19044053"/>
            <xs:enumeration value="20043025"/>
            <xs:enumeration value="19013791"/>
            <xs:enumeration value="17030058"/>
            <xs:enumeration value="19018354"/>
            <xs:enumeration value="19043744"/>
            <xs:enumeration value="19021768"/>
            <xs:enumeration value="19017008"/>
            <xs:enumeration value="18011022"/>
            <xs:enumeration value="20037715"/>
            <xs:enumeration value="19036593"/>
            <xs:enumeration value="18043234"/>
            <xs:enumeration value="16024164"/>
            <xs:enumeration value="18031244"/>
            <xs:enumeration value="19021551"/>
            <xs:enumeration value="18028840"/>
            <xs:enumeration value="19012039"/>
            <xs:enumeration value="19022133"/>
            <xs:enumeration value="19022012"/>
            <xs:enumeration value="19044236"/>
            <xs:enumeration value="19015219"/>
            <xs:enumeration value="20042408"/>
            <xs:enumeration value="19020403"/>
            <xs:enumeration value="18007506"/>
            <xs:enumeration value="19018469"/>
            <xs:enumeration value="19007654"/>
            <xs:enumeration value="19024876"/>
            <xs:enumeration value="19003635"/>
            <xs:enumeration value="19016621"/>
            <xs:enumeration value="19004794"/>
            <xs:enumeration value="19016354"/>
            <xs:enumeration value="19012828"/>
            <xs:enumeration value="19023685"/>
            <xs:enumeration value="19044097"/>
            <xs:enumeration value="19040327"/>
            <xs:enumeration value="19024821"/>
            <xs:enumeration value="17044501"/>
            <xs:enumeration value="19022932"/>
            <xs:enumeration value="18034544"/>
            <xs:enumeration value="18043164"/>
            <xs:enumeration value="19025363"/>
            <xs:enumeration value="19006973"/>
            <xs:enumeration value="19046762"/>
            <xs:enumeration value="19024473"/>
            <xs:enumeration value="19014274"/>
            <xs:enumeration value="18004854"/>
            <xs:enumeration value="18045748"/>
            <xs:enumeration value="19039010"/>
            <xs:enumeration value="19018590"/>
            <xs:enumeration value="19024208"/>
            <xs:enumeration value="19045646"/>
            <xs:enumeration value="19037878"/>
            <xs:enumeration value="19007694"/>
            <xs:enumeration value="19046155"/>
            <xs:enumeration value="19043611"/>
            <xs:enumeration value="18027561"/>
            <xs:enumeration value="18018121"/>
            <xs:enumeration value="19002456"/>
            <xs:enumeration value="19031569"/>
            <xs:enumeration value="18041536"/>
            <xs:enumeration value="19005557"/>
            <xs:enumeration value="19017505"/>
            <xs:enumeration value="19014397"/>
            <xs:enumeration value="19010752"/>
            <xs:enumeration value="18038133"/>
            <xs:enumeration value="17005393"/>
            <xs:enumeration value="19018178"/>
            <xs:enumeration value="19019028"/>
            <xs:enumeration value="19024020"/>
            <xs:enumeration value="19023415"/>
            <xs:enumeration value="18034316"/>
            <xs:enumeration value="19042388"/>
            <xs:enumeration value="19013480"/>
            <xs:enumeration value="17022030"/>
            <xs:enumeration value="19016680"/>
            <xs:enumeration value="19019430"/>
            <xs:enumeration value="19024137"/>
            <xs:enumeration value="18044844"/>
            <xs:enumeration value="19034418"/>
            <xs:enumeration value="15015043"/>
            <xs:enumeration value="19000915"/>
            <xs:enumeration value="20047269"/>
            <xs:enumeration value="19018087"/>
            <xs:enumeration value="19012586"/>
            <xs:enumeration value="19016582"/>
            <xs:enumeration value="19038159"/>
            <xs:enumeration value="19035326"/>
            <xs:enumeration value="18010889"/>
            <xs:enumeration value="19044224"/>
            <xs:enumeration value="17028007"/>
            <xs:enumeration value="19000148"/>
            <xs:enumeration value="20018041"/>
            <xs:enumeration value="18015138"/>
            <xs:enumeration value="19017297"/>
            <xs:enumeration value="19038861"/>
            <xs:enumeration value="19018938"/>
            <xs:enumeration value="19028545"/>
            <xs:enumeration value="18026817"/>
            <xs:enumeration value="99999999"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cmpType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Refactor the data set using XML and XML-Schema"/>
            <xs:enumeration value="Build and integrate a comments widget using local data and the Twitter API"/>
            <xs:enumeration value="Build and integrate a photo widget"/>
            <xs:enumeration value="Document the code and the system"/>
            <xs:enumeration value="Refactor the front-end to be responsive"/>
            <xs:enumeration value="Refactor the application to a (micro) PHP framework"/>
            <xs:enumeration value="Refactor the application to a Single Page Application (SPA)"/>
            <xs:enumeration value="Use and Document a Test FrameworkRefactoring to SPA"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="txtType">
        <xs:restriction base="xs:string">
            <xs:minLength value="140"/>
            <xs:maxLength value="12000"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="hours_effortType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="120"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>
<!-- DSA Individual Schema File, 2020/21 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== Auragen-dev/twin-cities-project/Xml's/19018469.xml
<?xml version="1.0" encoding="UTF-8"?>
<individual_metafile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ind_schema.xsd">
    <!--
 This file is an example of a valid individual metadata file. 
    Use this example file as a template and fill with your own data 
    validating as you go along using Oxygen or some other schema aware editor 
-->
    <group id="U" />
    <student id="19018469" />
    <!--
- List of one or more group components that you contributed to 
-->
    <component type="Refactor the front-end to be responsive">
        <description>
            Refactoring the front-end of our application to be responsive. Using a CSS framework, CSS, Javascript and other tools (icon libraries etc.).
        </description>
        <problems>
            1. On the server side there was a many to many issue. Some places had two categories.
            It was resolved however but it kept printing outside of the "boxes" I set for the place data.
            
            2. I originally misread the brief and it turned out I had to make use of a CSS Framework.
            
            3. In order to create HTML for the PHP data we made use of 'echo'. However, at times it made it difficult to develop. 
            For example, getting the quote marks to match up was difficult in areas.
            Another example being the IDE I was using (Brackets) couldn't tell me what tags were closed by what tags. When run it worked just fine but the IDE didn't understand this.
        </problems>
        <solutions>
            1. The place data was being echoed via a loop. I figured out this second category was being printed on its own on a second loop.
            So if a place had two categories, it would echo all the data in one loop, loop again and echo the second category without any other data or tags accociated with it.
            So sort this out I wrote some JavaScript to store the category and re-write the original echoed category with the second category placed in there.
            
            2. Since I had experience in bootstrap before I decided to spend a while reading over it and then started redoing the pages mostly from scratch.
            I kept some of my orignal CSS and JavaScript for things bootstrap couldn't provide. Such as the curtain menu in the RSS page.
            
            3. First of all I learned that you can put a php closing tag ('?>') and the HTML will still get printed on each loop. 
            Then I learned about the =?> tag to put the PHP data in. This made development much easier in general.
        </solutions>
        <hours_effort>15</hours_effort>
        <technologies>
            <tech>css</tech>
            <tech>javascript</tech>
            <tech>html5</tech>
            <tech>php</tech>
        </technologies>
        <source_files>
            <file>
                <name>css.css</name>
                <purpose>Contains the external CSS that wasn't provided by Bootstrap.</purpose>
            </file>
            <file>
                <name>js.js</name>
                <purpose>Stores some JavaScript functions we needed for some functionallity.</purpose>
            </file>
            <file>
                <name>RSSFeed.php</name>
                <purpose>Main application file. I made some custom dropdowns to make the data more presentable.</purpose>
            </file>
        </source_files>
    </component>
    <security_discussion>
        The four attributes I will be focusing on are Availability, Authenticity, Utility and Integrity
        With Availability we need to make sure our data sources are accessible by the website as much as possible. While it makes sense to store everything in-house, depending on the use case (such as this website) it would be more practical to reach out to other services. Because there is so much data, and different types of data, we have to deal with, it’s not possible to gather this much data in the time we have to make the website. Especially since other people have already done the hard work for us. We might as well take advantage of that. 
        
        With Integrity we should make an effort to minimise Cross Site Scripting (XSS) and SQL Injection where possible as both of these exploits can manipulate the data. XSS alone could jeopardize not only the data the user receives but could also jeopardize the user themselves. We can minimise XSS by escaping/filtering any text input by the user as well as encoding the output of the data. The simplest thing we can do to minimise SQL injection is to, again, escape all the text inputs by the user. We can also setup the SQL to recognise SQL queries and stop processing the query when it pops up.
        
        With Authenticity it goes back to Availability where we need to pick our sources carefully. Except this time, it is not to make sure the data is accessible, it is to make sure the data is accurate. For example, it would not make sense to pick a Weather API that can only return the weather of New York when we need the weather data for Leeds. Simple example, but still. We should also need to pick a source that is not compromised by an attacker. In theory they could encode JavaScript into the data that. And since it’s JavaScript, they can make it do anything from changing the data that is shown, or even installing malware on the user’s computer without their knowledge and permission.
        
        With Utility we need to make sure that all the other three attributes are ensured. This is because the webpage would not do anything if it had no data to access, it would not make sense to use a website that is compromised and could rick breaking your device and what is the point of using data if that data is not correct or accurate. 
    </security_discussion>
    <individual_comment>
        Going into my individual task, I had a lot of experience with CSS. I loved CSS. I hated JavaScript. I still love CSS but JavaScript has definately grown on me. For some reason I could never get it to work. But during this it was very cooperative.
    </individual_comment>
</individual_metafile>
<!-- DSA Individual Metadata File Example, 2020-1 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== Auragen-dev/twin-cities-project/Xml's/19034418.xml
<individual_metafile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ind_schema.xsd">
<group id="U"/>
<student id="19034418"/>
<component type="Refactor and map to a NoSQL ">
<description>
Refactoring the data of Leeds and Brno. Using MongoDB.
</description>
<problems>
The procedure of launching Mongo through terminal is complicated. 
As it required to run command first then followed by install Mongo Shell and Mongodb Compass.
</problems>
<solutions>
Going step by step and I have to make sure codes run correctly.
</solutions>
<hours_effort>10</hours_effort>
<technologies>
<tech>json</tech>
</technologies>
<source_files>
<file>
<name>cities_database.json</name>
<purpose>In put Twin Cities data both Leeds and Brno then recode them.</purpose>
</file>
</source_files>
</component>
<security_discussion>
 The four attributes I will be focusing on are Confidentiality, Integrity, Availability and Utility
 
</security_discussion>
<individual_comment>
I found out some parts are challenging to me as I don't have much experience in-depth details. It took me a while to understand how it will works.
</individual_comment>
</individual_metafile>

=== Auragen-dev/twin-cities-project/Xml's/19018087.xml
<?xml version="1.0" encoding="UTF-8"?>
<individual_metafile xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ind_schema.xsd">
<!--
 This file is an example of a valid individual metadata file. 
    Use this example file as a template and fill with your own data 
    validating as you go along using Oxygen or some other schema aware editor 
-->
<group id="U"/>
<student id="19018087"/>
<!--
- List of one or more group components that you contributed to 
-->
<component type="Build and integrate a comments widget using local data and the Twitter API">
<description>
Build and integrate a comments widget using local data and use the Twitter API to pull and display tweets, getting tweets about our twin cities.
</description>
<problems>

</problems>
<solutions>
    
</solutions>
<hours_effort>15</hours_effort>
<technologies>
<tech>php</tech>
<tech>json</tech>
<tech>html5</tech>
<tech>mysql</tech>
</technologies>
<source_files>
<file>
<name>[name of file]</name>
<purpose>[what does it do?]</purpose>
</file>
<file>
<name>[name of file]</name>
<purpose>[what does it do?]</purpose>
</file>
</source_files>
</component>
<security_discussion>
The four attributes I will be focusing on are 

</security_discussion>
<individual_comment>
The project was:
</individual_comment>
</individual_metafile>
<!-- DSA Individual Metadata File Example, 2020-1 -->
<!-- author: prakash.chatterjee@uwe.ac.uk -->

=== Auragen-dev/twin-cities-project/Xml's/19008369.xml
<individual_metafile xsi:noNamespaceSchemaLocation="ind_schema.xsd">
<group id="U"/>
<student id="19008369"/>
<component type="Build and integrate a photo widget">
<description>
Using the Flickr API to grab photos relevant to Leeds and Brno (twinned cities/towns) and integrate the component with the main application. Also add an option to upload your own images.
</description>
<problems>
Only using the correct licenced photos, for example, photos with a creative commons licence.
Cache
Getting used to Flickr, most examples used python and I wanted to stick with PHP, and getting used to grabbing information.
If you uploaded an image, you would get stuck on the uploads page.
</problems>
<solutions>
Adding another button to the form for licensing (changes the call to flickr), to show that our application only uses the correct creative common licenses, but also showing what the output would be if you allowed for any license.
Trying different ways to cache, using SQL and PHPMyAdmin, using arrays, and also trying to create files to refrence.
Messing around with Flickr for a few hours, getting outputs as XML (REST), JSON and PHP Serial, and seeing which I liked to work with the most.
Added a back button to the uploads page, so the user can go back to the main application.
</solutions>
<hours_effort>15</hours_effort>
<technologies>
<tech>php</tech>
<tech>json</tech>
<tech>html5</tech>
<tech>sql</tech>
</technologies>
<source_files>
<file>
<name>photos.php</name>
<purpose>to fetch flickr photos</purpose>
</file>
<file>
<name>RSSFeed.php</name>
<purpose>main page with embedded photos</purpose>
</file>
</source_files>
</component>
<security_discussion>
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
</security_discussion>
<individual_comment>
This part was harder than I thought it was going to be, as I had to try different ways to pull photos to get the best outcome, meaing I spent a lot of time going backwards and forwards editing little things in the application.
It took a few weeks to get it working the way I wanted, and that didn't include cache at the time.
I messed around with caching for weeks, never getting the exect outcome I wanted.
</individual_comment>
</individual_metafile>
